use_frameworks!

platform :ios, '8.0'

target 'SLCategoryObjCKit_Example' do
  pod 'SLCategoryObjCKit', :path => '../'

  target 'SLCategoryObjCKit_Tests' do
    inherit! :search_paths

    
  end
end
